// <auto-generated />
using System;
using AppServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppServices.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20260212100325_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("AppServices.CommuteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarAdditionalPassengers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarAverageConsumptionLPer100Km")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int>("CarDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarSpentEur")
                        .HasColumnType("REAL");

                    b.Property<int>("ChosenTravelMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DecisionVerdict")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DepartureUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EurPerMinutePerPerson")
                        .HasColumnType("REAL");

                    b.Property<bool>("PublicDelayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ScheduledArrivalUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Commutes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
