/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommuteStatisticsDto } from '../../models/commute-statistics-dto';

export interface CommutesStatisticsGet$Params {
}

export function commutesStatisticsGet(http: HttpClient, rootUrl: string, params?: CommutesStatisticsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<CommuteStatisticsDto>> {
  const rb = new RequestBuilder(rootUrl, commutesStatisticsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommuteStatisticsDto>;
    })
  );
}

commutesStatisticsGet.PATH = '/commutes/statistics';
