/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommuteDetailsDto } from '../../models/commute-details-dto';

export interface CommutesImportPost$Params {
      body: {
'file': Blob;
}
}

export function commutesImportPost(http: HttpClient, rootUrl: string, params: CommutesImportPost$Params, context?: HttpContext): Observable<StrictHttpResponse<CommuteDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, commutesImportPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommuteDetailsDto>;
    })
  );
}

commutesImportPost.PATH = '/commutes/import';
