/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarCommuteDto {
  additionalPassengers: number | null;
  averageConsumptionLPer100Km: number;
  distanceKm: number;
  durationMinutes: number;
  spentEur: number;
}
