/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommuteListItemDto {
  carDurationMinutes: number;
  chosenTravelMethod: string;
  decisionVerdict: string | null;
  departureUtc: string;
  destination: string;
  eurPerMinutePerPerson: number | null;
  id: number;
  publicDurationMinutes: number;
}
