/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarCommuteDto } from '../models/car-commute-dto';
import { CommuteAnalysisDto } from '../models/commute-analysis-dto';
import { PublicCommuteDto } from '../models/public-commute-dto';
export interface CommuteDetailsDto {
  analysis: CommuteAnalysisDto | null;
  car: CarCommuteDto;
  chosenTravelMethod: string;
  departureUtc: string;
  destination: string;
  id: number;
  public: PublicCommuteDto;
  scheduledArrivalUtc: string | null;
}
