/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommuteStatisticsDto {
  avgDurationCar: number;
  avgDurationPublic: number;
  avgFuelCostCarChosen: number | null;
  badDecisionsCount: number;
  countCarChosen: number;
  countPublicChosen: number;
  goodDecisionsCount: number;
  totalCo2Grams: number;
  totalDelaysPublic: number;
  totalFuelLitersCarChosen: number;
  totalKmCarChosen: number;
  totalSavedEur: number;
  totalSpentEur: number;
}
