/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type CommuteAnalysisDto = {
'carArrivalUtc': string;
'publicArrivalUtc': string;
'carPoints': number;
'publicPoints': number;
'decisionVerdict': string;
'eurPerMinutePerPerson': number | null;
};

